### ISSUE TITLE
"import AIC as ai;",What does it mean?

### ISSUE THREAD

**Issue by HaoVictory** [sumanth-bmsce/Unsupervised_Extreme_Learning_Machine#1]

**Comment by sumanth-bmsce** [comment]
AIC is Akaike Information Criterion which is used to find the optimal number of clusters on the dataset like Bayesian Information Criterion (BIC)

**Comment by HaoVictory** [comment]
Sorry,but I&nbsp; Could not find AIC module in python.Could you tell me how to import this module in ELM.py?And what is&nbsp; the significance of this AIC module in this ELM.py?

**Comment by sumanth-bmsce** [comment]
For now you can ignore that importing AIC module and pass number of clusters explicitly. Eg : k.k_means(output_matrix, 4) if no of clusters you want is 4

**Comment by HaoVictory** [comment]
Thank you very much for your help! I will try it.&nbsp;
